### ISSUE TITLE
How to remove border around images?

### ISSUE THREAD

**Issue by dfwdraco76** [MrReSc/MindTheDark#13]
Is there a simple way (something in userstyle.css maybe?) to remove the border around images?

![image](https://user-images.githubusercontent.com/30734939/119205246-5c685b80-ba5d-11eb-8d3f-8f0459628673.png)

I reverted to the default theme/template and the border went away, so I'm pretty sure it's specific to MidTheDark.

Thank you!!

**Comment by MrReSc** [comment]
Yes, the border comes from the template.
If you add the following lines to `conf/userstyle.css`, the border will no longer be displayed:

```
.dokuwiki img.media {
    border: none;
}
```
After that you have to reload the page with `CTRL + F5` or maybe even delete the cache of your browser.

If you don't like the spacing around the image, you can also play with `margin` and `padding`.
```
.dokuwiki img.media {
    border: none;
    margin: .2em 0;
    padding: 5px;
}
```
Tip: Maybe you should have a look at how the inspector mode of your browser works (usually `F12`). This way you can quickly find the corresponding CSS selectors.

**Comment by dfwdraco76** [comment]
> Tip: Maybe you should have a look at how the inspector mode of your browser works (usually `F12`). This way you can quickly find the corresponding CSS selectors.

Thanks, this did the trick:

```
.dokuwiki img.media {
    border: none;
    margin: .2em 0;
    padding: 0px;
}
```
