### ISSUE TITLE
If userChoice and autoDark are activated, the system color is no longer automatically used.

### ISSUE THREAD

**Issue by Gamemap** [MrReSc/MindTheDark#14]
If the functions userChoice and autoDark are activated you can toggle the design only with the button. The system setting is no longer used as the default.

Can the autoDark setting be the default until Toggle design is changed by a user?

**Comment by MrReSc** [comment]
Yes, the two functions do not work together.

Basically, you could do it the way you suggest. 
Currently I don't have time to make the extension. But I am open for a PR.

**Comment by Gamemap** [comment]
Can you tell me where I can find the code to detect the system theme?

**Comment by MrReSc** [comment]
Basically detects which theme the system uses, is in the CSS. In addition, however, the corresponding setting must also be made in the DokuWiki.
https://github.com/MrReSc/MindTheDark/blob/b410b4f788ca07eecd02cd957b23cb7b5e8df5b4/css/_autocolor.less#L52-L74

If the user selects something else, it will be saved in the local storage of the browser. You will certainly have to look at that as well.
https://github.com/MrReSc/MindTheDark/blob/b410b4f788ca07eecd02cd957b23cb7b5e8df5b4/script.js#L81-L123
