### ISSUE TITLE
"Template Style Settings" change the original template not MindTheDark Template

### ISSUE THREAD

**Issue by vbrozik** [MrReSc/MindTheDark#16]
In the "Template Style Settings" in the Admin section of DokuWiki (`doku.php?do=admin&page=styling`) I always see and set the colours of the original template not MindTheDark. I am unable to access the colour setting for the MindTheDark theme.

This happens also if I disable `autoDark` and `userChoice`.

Information about the system:
```
version	Release 2020-07-29 "Hogfather"
os	Linux
webserver	Apache/2.4.41 (Ubuntu)
php_version	7.4.3
```

MindTheDark Template
Download URL: github.com/MrReSc/MindTheDark/archive/2021-05-22.zip
Repository: github.com/MrReSc/MindTheDark
Installed version: 2021-05-22
Your last update: Thu, 08 Jul 2021 15:10:39 +0200

PS: MindTheDark is great but some grey backgrounds (like the frame / border) are too light and some darker text colours (like the blue links) are too dark. This makes them very hard to read? Would you mind changing the default colours to make the theme more readable?

**Comment by MrReSc** [comment]
> In the "Template Style Settings" in the Admin section of DokuWiki (doku.php?do=admin&page=styling) I always see and set the colours of the original template not MindTheDark. I am unable to access the colour setting for the MindTheDark theme.

Unfortunately, I cannot reproduce this. When I open the template styling settings (`docu.php?do=admin&page=styling`) I can set all colors for the light and the dark theme.

![grafik](https://user-images.githubusercontent.com/24952268/145932912-573f9edd-4b27-4711-b363-f3d34ac722ff.png)
How does that look to you?

> PS: MindTheDark is great but some grey backgrounds (like the frame / border) are too light and some darker text colours (like the blue links) are too dark. This makes them very hard to read? Would you mind changing the default colours to make the theme more readable?

If you make a suggestion that I like, I'll be happy to change the default values. I also find the link color a bit too dark. It's best if you also do a PR.

**Comment by MrReSc** [comment]
I have adjusted some default colors. Can you test the latest version from here?

https://github.com/MrReSc/MindTheDark/archive/refs/heads/master.zip

![grafik](https://user-images.githubusercontent.com/24952268/146395747-9b421ce4-b598-4e5f-9c4b-fc95add971f8.png)
