### ISSUE TITLE
Confirm compatibility with Release 2022-07-31 "Igor"

### ISSUE THREAD

**Issue by PacifistRiot** [MrReSc/MindTheDark#21]
2022-07-31 "Igor" has been released. Can we get confirmation that this theme is compatible with the new release?

**Comment by MrReSc** [comment]
I haven't tried it yet. Maybe you can test it and give me some feedback.

**Comment by PacifistRiot** [comment]
Been using it for 15 days. Haven't seen any issues with it yet.
