### ISSUE TITLE
I found a bug while open image attached on a page: Page style become light

### ISSUE THREAD

**Issue by DragonSerW** [MrReSc/MindTheDark#23]
https://dragonserw.ru/start?do=admin&page=config#tpl____mindthedark____tpl_settings_name:
'Color scheme if autoDark is disabled.': light
All other settings: checked.

Hello!
For example:
I open page https://dragonserw.ru/offero:dust-removing ('**link a**') then click on embedded image (id est https://dragonserw.ru/_detail/store:img_0098.jpg?id=offero%3Adust-removing -- '**link b**').
And the bug is:
While the content of **link a** is dark, the content of **link b** is light.
I can toggle theme on **link b** but for the first time light strikes my eyes -- that is not so good you know.
My English is not so fluent -- take notice of that :-)) Thanks! )

I had posted this issue on DW Forum: https://forum.dokuwiki.org/d/20508-mindthedark-i-found-a-bug-while-open-image-attached-on-a-page.

**Comment by MrReSc** [comment]
I can reproduce it, thanks for reporting it.
I will take care of it.
