### ISSUE TITLE
does not work.

### ISSUE THREAD

**Issue by ThirtySix361** [MrReSc/MindTheDark#27]
i have installed the template.
activated the template in the konfiguration.
but color doesnt change to darkmode.
and i do not have a toggle button at the top to switch anything.

only the width of site becomes 100%

**Comment by MrReSc** [comment]
It is almost impossible to help you without any information about your system, the DokuWiki and the version of MTD.

But I would clear the browser cache and reload the page or press Ctrl + F5 to reload the page.

**Comment by MrReSc** [comment]
You also need to configure the template, not just activate it.
