### ISSUE TITLE
Syntax highlighting for code?

### ISSUE THREAD

**Issue by pv2b** [MrReSc/MindTheDark#4]
As you can already see on the ![screenshot](screenshot/screenshot.png) in the documentation, syntax highlighting for code ends up looking not so good on a dark background.

Seems DokuWiki uses GeSHi for syntax highlighting, and there's some work done for some other software also using GeSHi on how to make it work well with dark mode that might be possible to take advantage of:

https://cyberasylum.eu/how-to-change-geshi-stylesheet

**Comment by MrReSc** [comment]
Implemented with PR #5
