### ISSUE TITLE
Dark theme flickers on page change

### ISSUE THREAD

**Issue by manicmoose** [MrReSc/MindTheDark#8]
Hi,

Firstly, great theme!

When the "tpl»mindthedark»userChoice" configuration button is 'ticked' and you have the dark mode selected - every time you click a link to change to another page, it flickers white then goes to the dark theme.

If you've unselected "tpl»mindthedark»userChoice" and are still using the dark mode, the flickering doesn't happen.

I'm guessing that white is the 'default' mode, and probably needs a css solution to resolve this.

Cheers.

**Comment by MrReSc** [comment]
Unfortunately, I cannot recreate the behaviour. What browser do you use? Do you have any plugins in your browser that automatically show websites in a dark theme?

**Comment by MrReSc** [comment]
The plugin was actually only tested by me with Firefox. 
I also only use Firefox. With me it works without problems.
What kind of OS do you use? I used Fedora 33.

**Comment by MrReSc** [comment]
The plugin was actually only tested by me with Firefox. 
I also only use Firefox. With me it works without problems.
What kind of OS do you use? I used Fedora 33.

**Comment by MrReSc** [comment]
> Interesting - I'm using Firefox - and no plugins to impose dark mode.
> 
> I tried it in Chrome and it **doesn't** happen, so I disabled ALL my extensions and theme (dark theme) in FF and it still occurs.
> Tested in a FF private window (ie. most things disabled) and again, it still happens.
> Tested in Safari (no plugins whatsoever as I never use Safari) and it also happens.
> 
> Odd.

The plugin was actually only tested by me with Firefox. I also only use Firefox. With me it works without problems.
What kind of OS do you use? I used Fedora 33.

**Comment by MrReSc** [comment]
The plugin was actually only tested by me with Firefox. 
I also only use Firefox. With me it works without problems.
What kind of OS do you use? I used Fedora 33.

**Comment by manicmoose** [comment]
Interesting - I'm using Firefox - and no plugins to impose dark mode.

I tried it in Chrome and it **doesn't** happen, so I disabled ALL my extensions and theme (dark theme) in FF and it still occurs.
Tested in a FF private window (ie. most things disabled) and again, it still happens.
Tested in Safari (no plugins whatsoever as I never use Safari) and it also happens.

Odd.

**Comment by MrReSc** [comment]
The plugin was actually only tested by me with Firefox.
I also only use Firefox. With me it works without problems.
What kind of OS do you use? I used Fedora 33.

**Comment by manicmoose** [comment]
Hmm...I'm using it on a Hackintosh.
Perhaps I'll boot up linux or Windoze and see what (if any) difference there is.

It's not a big deal as I can just disable the user choice option and the problem goes away.
To the naked eye, it looks like it's rendering the page in white first, then quickly re-renders it in the dark theme.

**Comment by Gamemap** [comment]
I have the same issue too.

OS: Windows 10 64-Bit
Firefox: Version 95.0 (64-Bit)

This also happens if you have selected the light mode and enabled autoDark.

https://user-images.githubusercontent.com/71942164/145672453-4d77772f-1744-40e0-8c19-d801235992f6.mp4

**Comment by MrReSc** [comment]
Now I have the problem with me too. @Gamemap maybe you have time to find a permanent solution for this problem?

**Comment by MrReSc** [comment]
Here the problem seems to be that the server (PHP code) already generates and delivers the HMTL and only in the browser is decided which theme to use. Somehow the display of the website would have to wait until the JS code was executed. Any ideas?

**Comment by Gamemap** [comment]
This text says that you should use cookies to avoid flickering.
https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#using-cookies-with-php

**Comment by vbrozik** [comment]
Just to describe the behaviour on my system:
Client: Windows 10, Chrome 96.0 (happens with clean profile)

I see the bright flashes only when going back in the browsing history or saving DokuWiki configuration (that does not matter much). **When I disable the user selection of the theme then the flashes do not happen.**

@MrReSc
So if I understand it correctly on a newly loaded page a JS code must be run to decide which theme to use? Before that the default theme is used? If so then probably the server should remember the user preference and use the theme according to that.

Suggesting a (probably) small change for a little better behaviour: The first displayed theme (before the JS) should be the one set in the settings. Then the flashes would happen only for users who override the default setting.

**Comment by MrReSc** [comment]
> So if I understand it correctly on a newly loaded page a JS code must be run to decide which theme to use? Before that the default theme is used? If so then probably the server should remember the user preference and use the theme according to that.

Yes, exactly.

> Suggesting a (probably) small change for a little better behaviour: The first displayed theme (before the JS) should be the one set in the settings. Then the flashes would happen only for users who override the default setting.

That's what I was thinking. Or you always use the automatic mode. This is probably even closer to what the user wants.

**Comment by MrReSc** [comment]
The problem is with the [deferred loading](https://www.dokuwiki.org/config:defer_js) that is turned on by default since the latest version. When this is turned off, it no longer flickers.

As an intermediate solution you can set `defer_js = false`.

![grafik](https://user-images.githubusercontent.com/24952268/145985268-9e3091f1-92b4-49dd-b29e-11765ef6f192.png)

**Comment by MrReSc** [comment]
I tried to solve the problem using cookies instead of localstorage. It looks quite good. @vbrozik @Gamemap @manicmoose Can you try the latest version?

https://github.com/MrReSc/MindTheDark/archive/refs/heads/master.zip

**Comment by manicmoose** [comment]
Legendary - you fixed it.  Nice work!
Thanks for your that - I'd almost forgotten about it... ;-)

**Comment by Gamemap** [comment]
I think you fixed it (I will test it more detailed soon) but because you don't load the ' tpl_autocolor.php' it isen't possible to change the Note Plugin to dark mode.

**Comment by MrReSc** [comment]
Yes, that's right. I forgot about that. I have to fix that too.
